name: Dynamic Token Fetch Example

on:
  push:

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Fetch the token using GitHub API with PAT_TOKEN
      - name: Fetch Runner Token
        run: |
          echo "Fetching runner token..."
          TOKEN=$(curl -X POST -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/runners/registration-token | jq -r .token)
           
          if [ -z "$TOKEN" ]; then
            echo "Failed to fetch token."
            exit 1
          fi
          
          echo "Token fetched: $TOKEN"
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      # Use the token fetched
      - name: Use the Token
        run: |
          echo "Using the fetched token..."
          echo "The runner token is: ${{ env.TOKEN }}"
